window.DESK_ORB_SOCIAL = [
  {
    id: "bilibili",
    name: "哔哩哔哩",
    logo: "bilibili",
    handle: "UID 3546867614878349",
    profileUrl: "https://space.bilibili.com/3546867614878349",
    nickname: "B站账号",
    avatarText: "B",
    followers: 12,
    color: "#00a1d6",
    accent: "#f6fbff",
    note: "公开资料：昵称、头像、粉丝数。",
  },
  {
    id: "douyin",
    name: "抖音",
    logo: "douyin",
    handle: "抖音号 63230246827",
    profileUrl: "https://www.douyin.com/user/MS4wLjABAAAAaUGAN5swqwZMFuriuXXeScUcZzH1j5ndwD4Gzv4Zd9Bv7LoAFHmQIS0IAX7Ouodp?from_tab_name=main",
    nickname: "抖音号 63230246827",
    avatarText: "抖",
    followers: 0,
    color: "#111827",
    accent: "#ff2e63",
    note: "已配置主页链接，等待公开数据同步。",
  },
  {
    id: "toutiao",
    name: "今日头条",
    logo: "toutiao",
    handle: "仙翁777",
    profileUrl: "https://www.toutiao.com/c/user/token/CizUGDjTPuJYRMOhlDkdXL8xsa39ne_PlyoibC8UUJuXqTydoGl2_SI-rYQnwBpJCjwAAAAAAAAAAAAAUKQRThn1KrIcHHVtQ8jtH1FFQLtb95i6b--tMSTCc6buo8LknRThC8MD6wNKYzgSnN8Q47WWDhjDxYPqBCIBA0AOo8M=/?tab=weitoutiao",
    nickname: "仙翁777",
    avatarText: "头",
    followers: 0,
    color: "#d71920",
    accent: "#fff7ed",
    note: "已配置主页链接，等待公开数据同步。",
  },
];
